services:
  - type: web
    name: usdt-tatum-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 10000
      - key: ADMIN_SECRET_KEY
        generateValue: true
      - key: SUPABASE_URL
        fromValue: https://wedrdhnoioakdrzqsofw.supabase.co
      - key: SUPABASE_KEY
        sync: false
      - key: TATUM_API_KEY
        sync: false
      - key: TATUM_NETWORK
        value: BSC_TESTNET
      - key: MNEMONIC
        sync: false
      - key: USDT_CONTRACT_ADDRESS
        value: "0x55d398326f99059fF775485246999027B3197955"
      - key: MAIN_HOT_WALLET_ADDRESS
        sync: false
      - key: APP_URL
        fromContext: instance_url
